---
deployment:
  tasks:
    - export DEPLOYPATH=/home/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R classes $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
